# Generated by Django 4.0.2 on 2022-02-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todayblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='news_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
    ]
